### ISSUE TITLE
请问login中localStorage的数据路径在哪里呢？

### ISSUE THREAD

**Issue by dst111dst** [s649821022/epidemicweb#2]
抱歉打扰了，请问在src/api/user.js中调用login函数的时候，传入给post方法的"/api/v1/auth/login/"下的数据在哪里可以看到呀？有点困惑用户名和密码的传入形式以及存储路径。希望能得到解答，再次感谢！

**Comment by s649821022** [comment]
存储过程的代码在/src/store/modules/user.js中actions的那部分，主要关注（我注释了"用户登录下面的代码"），比如setUser(response.user)，它是调用/src/utils/auth.js/下的setUser方法，将user也就是用户名存储在localStorge中，你可以通过F12下的Application菜单，可以看到Storage中有个Local Storage，User的信息就存储在那里，Password也是同样如此，希望这个回答有能帮助到你


存储的方法就是使用localStorage.setItem，将你设置的内容存储在localStorage中，存储的过程使用Vuex




凯小杜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "s649821022/epidemicweb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 凌晨1:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[s649821022/epidemicweb] 请问login中localStorage的数据路径在哪里呢？ (Issue #2)





 
抱歉打扰了，请问在src/api/user.js中调用login函数的时候，传入给post方法的"/api/v1/auth/login/"下的数据在哪里可以看到呀？有点困惑用户名和密码的传入形式以及存储路径。希望能得到解答，再次感谢！

**Comment by s649821022** [comment]
存储过程的代码在/src/store/modules/user.js中actions的那部分，主要关注（我注释了"用户登录下面的代码"），比如setUser(response.user)，它是调用/src/utils/auth.js/下的setUser方法，将user也就是用户名存储在localStorge中，你可以通过F12下的Application菜单，可以看到Storage中有个Local Storage，User的信息就存储在那里，Password也是同样如此，希望这个回答有能帮助到你


存储的方法就是使用localStorage.setItem，将你设置的内容存储在localStorage中，存储的过程使用Vuex

**Comment by dst111dst** [comment]
感谢回复！收到～
